### PR TITLE
add userdata order_trade_update

### PR DESCRIPTION
**Pull request by StarBalll**
# PR Details

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the 
**[CONTRIBUTING](https://github.com/oliver-zehentleitner/unicorn-fy/blob/master/CONTRIBUTING.md)** 
document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by oliver-zehentleitner** [comment]
Hello @StarBalll

Thank you very much for you contribution!

I have to points to discuss:
1. can you please provide English comments instead of Chinese?
2. ACCOUNT_UPDATE is in "pass" mode :) that way i can release that ...
3. we have to add test units, i could do that, but would you be able to provide me the raw data of the new added events?

Best regards,
Oliver

**Comment by StarBalll** [comment]
[ex.txt](https://github.com/oliver-zehentleitner/unicorn-fy/files/6277747/ex.txt)

**Comment by oliver-zehentleitner** [comment]
Thanks a lot! :+1:

**Review by oliver-zehentleitner — COMMENTED** [review]
Thank you!

**Pull request merged**
